# Generated by Django 5.0.7 on 2024-07-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
